package com.example.st3.ui.theme

/**
 * Auto-generated from Pixso design tokens
 * Do not edit manually - run sync command in Cursor to update
 */
object PixsoStrings {
    const val Body_Body_L_Font = "IBM Plex Sans"
    const val Body_Body_L_Weight = "Regular"
    const val Body_Body_M_Font = "IBM Plex Sans"
    const val Body_Body_M_Weight = "Regular"
    const val Body_Body_S_Font = "IBM Plex Sans"
    const val Body_Body_S_Weight = "Regular"
    const val Button_Button_L_Font = "IBM Plex Sans"
    const val Button_Button_L_Weight = "Medium"
    const val Button_Button_M_Font = "IBM Plex Sans"
    const val Button_Button_M_Weight = "Medium"
    const val Button_Button_S_Font = "IBM Plex Sans"
    const val Button_Button_S_Weight = "Medium"
    const val Display_Display_L_Font = "IBM Plex Sans"
    const val Display_Display_L_Weight = "Regular"
    const val Display_Display_M_Font = "IBM Plex Sans"
    const val Display_Display_M_Weight = "Regular"
    const val Display_Display_S_Font = "IBM Plex Sans"
    const val Display_Display_S_Weight = "Regular"
    const val Font_Font_Family = "IBM Plex Sans"
    const val Font_Weight_Medium = "Medium"
    const val Font_Weight_Regular = "Regular"
    const val Font_Weight_SemiBold = "SemiBold"
    const val Headline_Headline_L_Font = "IBM Plex Sans"
    const val Headline_Headline_L_Weight = "Regular"
    const val Headline_Headline_M_Font = "IBM Plex Sans"
    const val Headline_Headline_M_Weight = "Regular"
    const val Headline_Headline_S_Font = "IBM Plex Sans"
    const val Headline_Headline_S_Weight = "Medium"
    const val Headline_Headline_XS_Font = "IBM Plex Sans"
    const val Headline_Headline_XS_Weight = "Medium"
    const val Label_Label_L_Font = "IBM Plex Sans"
    const val Label_Label_L_Weight = "Medium"
    const val Label_Label_M_Font = "IBM Plex Sans"
    const val Label_Label_M_Weight = "Medium"
    const val Label_Label_S_Font = "IBM Plex Sans"
    const val Label_Label_S_Weight = "Medium"
    const val Title_Title_L_Font = "IBM Plex Sans"
    const val Title_Title_L_Weight = "Regular"
    const val Title_Title_M_Font = "IBM Plex Sans"
    const val Title_Title_M_Weight = "Medium"
    const val Title_Title_S_Font = "IBM Plex Sans"
    const val Title_Title_S_Weight = "Medium"
}
